/**
 * AirportListController
 *
 * @description :: Server-side actions for handling incoming requests.
 * @help        :: See https://sailsjs.com/docs/concepts/actions
 */

module.exports = {
	//function used to save airportlist
	airportlist: function(req, res) {
		//get data into variables
		var id = req.body.inwardcargo_airport_list_id;
		var iataCode = req.body.inwardcargo_airport_list_iata_code_input;
		var cityName = req.body.inwardcargo_airport_list_city_name_input;
		var isInwardPort = req.body.inwardcargo_airport_list_is_inward_destination;

		//validations
		if (iataCode == undefined || iataCode == null || iataCode == '') {
			sails.log.error(req.user.username + ' - ' + new Date() +' ERR - (airportlist - post) IATA code cannot be blank');
			return res.send({error: 'IATA Code Cannot be blank', error_code:'ERR_AL_IATA_BLANK'});
		} else if (cityName == undefined || cityName == null || cityName == '') {
			sails.log.error(req.user.username + ' - ' + new Date() +' ERR - (airportlist - post) City name cannot be blank');
			return res.send({error: 'City Name Cannot be blank', error_code:'ERR_AL_CITY_BLANK'});
		} else {
			sails.log.info(req.user.username + ' - ' + new Date() +' INFO -  (airportlist - post) Airport validation successfully');
			//check for port if not found create new
			Ports.findOrCreate({ _id: id}, { iata_code: iataCode.toUpperCase() , city_name: cityName})
				.exec(async(err, ports, wasCreated)=> {
					if (err) {
						if (err.code == 'E_UNIQUE') {
							// duplicate value not allowed
							sails.log.error(req.user.username + ' - ' + new Date() +' ERR -  (airportlist - post)' + sails.config.globals.uniqueError);
							return res.send({error: sails.config.globals.uniqueError, error_code:'ERR_AL_E_UNIQUE'});
						} else {
							sails.log.error(req.user.username + ' - ' + new Date() +' ERR - ' + err);
							return res.send({error: 'Something Happend During Creating Record'});
						}
					} else {
						sails.log.info(req.user.username + ' - ' + new Date() +' INFO -  (airportlist - post) Airport found or created new if not found');
						//update airport
						Ports.update({_id:ports.id}, {is_inward_port: isInwardPort, iata_code: iataCode.toUpperCase() , city_name: cityName}).fetch()
							.exec(function(err, updatedAirport){
								if (err) {
									sails.log.error(req.user.username + ' - ' + new Date() +' ERR -  (airportlist - post)' + err);
									return res.send({error: 'Something Happens During Updating Or Inserting'});
								} else {
									sails.log.info(req.user.username + ' - ' + new Date() +' INFO -  (airportlist - post) Airport updated successfully');
									return res.send({value: updatedAirport[0]});
								}
							});
					}
				});
		}
	},
	// function used to get airportlist
	getairportlist: function(req, res) {
		//find all airports
		Ports.find({ where: {}, sort: 'iata_code'}, function(err, ports) {
			if (err) {
				sails.log.error(req.user.username + ' - ' + new Date() +' ERR -  (getairportlist - get) ' + err);
				return res.view('pages/imlost', {error: 'Error in finding airport list'});
			} else {
				sails.log.info(req.user.username + ' - ' + new Date() +' INFO -  (getairportlist - get) Airport found successfully');
				return res.view('pages/airport-list',{airportlistdetails: ports});
			}
		});
	},
	//delete airport
	deleteairport:function(req, res){
		var deletePortId = req.body.inwardcargo_airport_list_delete_airport;
		Ports.destroy({'_id' : deletePortId }).exec(function(err, ports){
			if(err) {
				sails.log.error(req.user.username + ' - ' + new Date() +' ERR -  (deleteairport - post) ' + err);
				return res.view('pages/imlost', {error: 'Error while finding the port while deleting'});
			} else {
				sails.log.info(req.user.username + ' - ' + new Date() +' INFO - (deleteairport - post) Airport deleted successfully');
				return res.send({result: true});
			}
		});
	},
	addairports: function(req, res) {

		sails.config.globals.async.waterfall([
			function(callback) {
				//	Adding Airports
				var cities = [
					["AAR","Aarhus",false],
["ABD","Abadan",false],
["AEH","Abeche",false],
["ABZ","Aberdeen",false],
["ABR","Aberdeen, SD",false],
["ABJ","Abidjan",false],
["ABI","Abilene, TX",false],
["AUH","Abu Dhabi",false],
["ABV","Abuja International",false],
["AUE","Abu Rudeis",false],
["ABS","Abu Simbel",false],
["ACA","Acapulco",false],
["ACC","Accra",false],
["ADA","Adana",false],
["ADD","Addis Ababa",false],
["ADL","Adelaide",false],
["ADE","Aden",false],
["AER","Adler/Sochi",false],
["AJY","Agades",false],
["AGA","Agadir",false],
["SUM","Agana",false],
["AGZ","Aggeneys",false],
["BQN","Aguadilla",false],
["AGU","Aguascaliente",false],
["AMD","Ahmedabad",false],
["AJA","Ajaccio",false],
["AXT","Akita",false],
["CAK","Akron, OH",false],
["AKT","Akrotiri - RAF",false],
["ADX","Aktyubinsk",false],
["AAN","Al Ain",false],
["AAC","Al Arish",false],
["AAC","Al Arish",false],
["ALH","Albany",false],
["ABY","Albany, GA",false],
["ALB","Albany, NY",false],
["LBI","Albi",false],
["AAL","Alborg",false],
["ABQ","Albuquerque, NM",false],
["ABX","Albury",false],
["AES","Alesund",false],
["ALJ","Alexander Bay",false],
["ALY","Alexandria, El Nhouza Airport",false],
["ESF","Alexandria, La",false],
//["FJR","Alfujairah (Fujairah)",false],
["AHO","Alghero Sassari",false],
["ALG","Algiers",false],
["AHU","Al Hoceima",false],
["ALC","Alicante",false],
["ASP","Alice Springs",false],
["ADY","Alldays",false],
["ABE","Allentown, PA",false],
["ALA","Alma Ata",false],
["LEI","Almeria",false],
["ALP","Aleppo",false],
["ALF","Alta",false],
["ACH","Altenrhein",false],
["AOO","Altoona, PA",false],
["ASJ","Amami",false],
["AMA","Amarillo, TX",false],
["AMM","Amman, Queen Alia Intl",false],
["ADJ","Amman, Civil - Marka Airport",false],
["ATQ","Amritsar",false],
["AMS","Amsterdam, Schiphol",false],
["QNB","Anand",false],
["ANC","Anchorage, AK",false],
["AOI","Ancona",false],
["ALV","Andorra La Vella H/P",false],
["AXA","Anguilla",false],
["AJN","Anjouan",false],
["ANK","Ankara",false],
["AAE","Annaba",false],
["ARB","Ann Arbor, MI",false],
["NCY","Annecy",false],
["ANB","Anniston, AL",false],
["AYT","Antalya",false],
["TNR","Antananarivo (Tanannarive)",false],
["ANU","Antigua",false],
["ANR","Antwerp",false],
["AOJ","Aomori",false],
["APW","Apia",false],
["ATW","Appelton/Neenah/Menasha, WI",false],
["AQJ","Aqaba",false],
["AJU","Aracaju",false],
["ARH","Arkhangelsk",false],
["ARK","Arusha",false],
["GPA","Araxos",false],
["RLT","Arlit",false],
["AXS","Armenia",false],
["ACE","Arrecife/Lanzarote",false],
["AUA","Aruba",false],
["AVL","Asheville, NC",false],
["ASB","Ashgabat, Ashkhabat",false],
["ASE","Aspen Snowmass, CO",false],
["ATZ","Assiut",false],
["TSE","Astana",false],
["ASU","Asuncion",false],
["ASW","Aswan, Daraw Airport",false],
["ATH","Athens",false],
["HEW","Athens, Hellinikon Airport",false],
["AHN","Athens, GA",false],
["ATO","Athens, OH",false],
["ATL","Atlanta, Hartsfield Atlanta Int'l Airport",false],
["ACY","Atlantic City, NJ",false],
["YAT","Attawapiskat, NT",false],
["AKL","Auckland",false],
["AGB","Augsburg",false],
["AGS","Augusta, GA",false],
["AUG","Augusta, ME",false],
["AUR","Aurillac",false],
["AUS","Austin, TX",false],
["AYQ","Ayers Rock",false],
["AYR","Ayr",false],
["BJZ","Badajoz",false],
["BGW","Bagdad, Al Muthana",false],
["SDA","Bagdad, Saddam International",false],
["IXB","Bagdogra",false],
["BHV","Bahawalpur",false],
["BAH","Bahrain",false],
["BFL","Bakersfield, CA",false],
["BAK","Baku",false],
["BNK","Ballina",false],
["BWI","Baltimore Washington Int'l Airport; MD",false],
["ABM","Bamaga",false],
["BKO","Bamako",false],
["BBY","Bambari",false],
["BWN","Bandar Seri Begawan",false],
["BLR","Bangalore",true],
["BGU","Bangassou",false],
["BKK","Bangkok",false],
["BGR","Bangor, ME",false],
["BGF","Bangui",false],
["BJL","Banjul",false],
["BNP","Bannu",false],
["BCN","Barcelona",false],
["BLA","Barcelona",false],
["BDU","Bardufoss",false],
["BRI","Bari",false],
["BZL","Barisal",false],
["BDQ","Baronda",false],
["BAQ","Barranquilla",false],
["BSL","Basel",false],
["EAP","Basel/Mulhouse",false],
["BSR","Basra, Basrah",false],
["BIA","Bastia",false],
["BTR","Baton Rouge, La",false],
["BYU","Bayreuth",false],
["BPT","Beaumont/Pt. Arthur, TX",false],
["BKW","Beckley, WV",false],
["EIS","Beef Island",false],
["PEK","Beijing",false],
["NAY","Beijing - Nanyuan Airport",false],
["BEW","Beira",false],
["BEY","Beirut",false],
["BEL","Belem",false],
["BHD","Belfast - Harbour",false],
["BFS","Belfast International",false],
["IXG","Belgaum",false],
["BEG","Belgrad (Beograd)",false],
["BZE","Belize City",false],
["BLI","Bellingham, WA",false],
["CNF","Belo Horizonte",false],
["BJI","Bemidji, MN",false],
["BEN","Bengasi",false],
["BUG","Bengueka",false],
["BEH","Benton Harbour, MI",false],
["BBT","Berberati",false],
["BGY","Bergamo",false],
["BGO","Bergen",false],
["BER","Berlin",false],
["SXF","Berlin, Schoenefeld",false],
["TXL","Berlin, Tegel",false],
["THF","Berlin, Tempelhof",false],
["BDA","Bermuda",false],
["BRN","Bern",false],
["ZDJ","Bern",false],
["BET","Bethel, AK",false],
["BHO","Bhopal",false],
["BBI","Bhubaneswar",false],
["BIQ","Biarritz",false],
["BIO","Bilbao",false],
["BIL","Billings, MT",false],
["BLL","Billund",false],
["BTU","Bintulu",false],
["IRO","Biraro",false],
["BHX","Birmingham",false],
["BHM","Birmingham, AL",false],
["BIS","Bismarck/Mandan, ND",false],
["BXO","Bissau",false],
["BLT","Blackwater",false],
["BLZ","Blantyre",false],
["BHE","Blenheim",false],
["BFN","Bloemfontein",false],
["BMI","Bloomington, IL",false],
["BMG","Bloomington, IN",false],
["BLF","Bluefield, WV",false],
["BVB","Boa Vista",false],
["BOY","Bobo/Dioulasso",false],
["BOO","Bodo",false],
["BOG","Bogota",false],
["BOI","Boise, ID",false],
["BLQ","Bologna",false],
["BOM","Mumbai",true],
["BON","Bonaire",false],
["YVB","Bonaventure, PQ",false],
["BOB","Bora Bora",false],
["BOD","Bordeaux",false],
["HBH","Borg El Arab Airport",false],
["BXS","Borrego Springs, CA",false],
["BOS","Boston - Logan, MA",false],
["BYK","Bouake",false],
["BOJ","Bourgas/Burgas",false],
["ZBO","Bowen",false],
["BZN","Bozeman, MT",false],
["BFD","Bradford/Warren, PA/Olean, NY",false],
["BRD","Brainerd, MN",false],
["BMP","Brampton Island",false],
["BSB","Brasilia",false],
["BTS","Bratislava",false],
["BZV","Brazzaville",false],
["BRE","Bremen",false],
["VBS","Brescia, Montichiari",false],
["BES","Brest",false],
["BIV","Bria",false],
["BDR","Bridgeport, CT",false],
["BGI","Bridgetown, Grantley Adams Int'l",false],
["BDS","Brindisi",false],
["BNE","Brisbane",false],
["BRS","Bristol",false],
["BNN","Broennoeysund",false],
["BHQ","Broken Hill",false],
["BKX","Brookings, SD",false],
["BME","Broome",false],
["BQK","Brunswick, GA",false],
["BRU","Brussels",false],
["BGA","Bucaramanga",false],
["BUD","Budapest, Ferihegy",false],
["BUE","Buenos Aires",false],
["EZE","Buenos Aires, Ezeiza Int'l Airport",false],
["AEP","Buenos Aires, Jorge Newbery",false],
["BFO","Buffalo Range",false],
["BUF","Buffalo/Niagara Falls, NY",false],
["BJM","Bujumbura",false],
["BUH","Bucharest",false],
["OTP","Bucharest, Otopeni",false],
["BUQ","Bulawayo",false],
["BHC","Bullhead City, NV",false],
["BDB","Bundaberg",false],
["BUR","Burbank, CA",false],
["BRL","Burlington, IA",false],
["BTV","Burlington, VT",false],
["BWT","Burnie (Wynyard)",false],
["BTM","Butte, MT",false],
["CAB","Cabinda",false],
["CAG","Cagliari",false],
["CNS","Cairns",false],
["CAI","Cairo Int'l",false],
["CCU","Calcutta (Kolkata) - Netaji Subhas Chandra",false],
["KMQ","Komatsu",false],
["YYC","Calgary/Banff",false],
["CLO","Cali",false],
["CCJ","Calicut",false],
["CLY","Calvi",false],
["YCB","Cambridge Bay",false],
["CBG","Cambrigde",false],
["CGR","Campo Grande",false],
["CBR","Canberra",false],
["CUN","Cancun",false],
["CPT","Cape Town",false],
["CCS","Caracas",false],
["CWL","Cardiff",false],
["CLD","Carlsbad, CA",false],
["CVQ","Carnarvon",false],
["CRF","Carnot",false],
["LRM","Casa de Campo/La Romana",false],
["CAS","Casablanca",false],
["CMN","Casablanca, Mohamed V",false],
["CSI","Casino",false],
["CPR","Casper, WY",false],
["CTG","Catagena",false],
["CTA","Catania",false],
["CAY","Cayenne",false],
["CBU","Cebu",false],
["CDC","Cedar City, UT",false],
["CID","Cedar Rapids, IA",false],
["CED","Ceduna",false],
["CES","Cessnock",false],
["KHV","Chabarovsk (Khabarovsk)",false],
["CMF","Chambery",false],
["CMI","Champaign, IL",false],
["IXC","Chandigarh",false],
["CGQ","Changchun",false],
["CHQ","Chania",false],
["CHS","Charleston, SC",false],
["CRW","Charleston, WV",false],
["CLT","Charlotte, NC",false],
["CHO","Charlottesville, VA",false],
["CXT","Charters Towers",false],
["CHA","Chattanooga, TN",false],
["CTU","Chengdu",false],
["MAA","Chennai (Madras)",true],
["CYS","Cheyenne, WY",false],
["CNX","Chiang Mai",false],
["QCB","Chiba City",false],
["MDW","Chicago, Midway, IL",false],
["ORD","Chicago O'Hare Int'l Airport, IL",false],
["CHI","Chicago, IL",false],
["CZA","Chichen Itza",false],
["CIC","Chico, CA",false],
["CUU","Chihuahua, Gen Fierro Villalobos",false],
["JKH","Chios",false],
["CIP","Chipata",false],
["HTA","Chita (Tschita)",false],
["CTS","Chitose",false],
["CJL","Chitral",false],
["CGP","Chittagong",false],
["CKG","Chongqing",false],
["CHC","Christchurch",false],
["CXI","Christmas Line",false],
["CCZ","Chub Cay",false],
["YYQ","Churchill",false],
["CFG","Cienfuegos",false],
["CVG","Cincinnati, OH",false],
["CME","Ciudad Del Carmen",false],
["CJS","Ciudad Juarez",false],
["CEN","Ciudad Obregon",false],
["CVM","Ciudad Victoria",false],
["CKB","Clarksburg, WV",false],
["CMQ","Clermont",false],
["CFE","Clermont Ferrand",false],
["BKL","Cleveland, Burke Lakefront, OH",false],
["CLE","Cleveland, Hopkins, OH",false],
["CBB","Cochabamba",false],
["COK","Cochin",false],
["COD","Cody/Powell/Yellowstone, WY",false],
["KCC","Coffmann Cove, AK",false],
["CFS","Coffs Harbour",false],
["CJB","Coimbatore",false],
["CLQ","Colima",false],
["CLL","College Station/Bryan, TX",false],
["KCE","Collinsville",false],
["CGN","Cologne (Koeln)/Bonn",false],
["CMB","Colombo",false],
["COS","Colorado Springs, CO",false],
["CAE","Columbia, SC",false],
["CSG","Columbus, GA",false],
["CMH","Columbus, OH",false],
["CKY","Conakry",false],
["CCR","Concord, CA",false],
["CZL","Constantine",false],
["CND","Constanza",false],
["CPD","Coober Pedy",false],
["CTN","Cooktown",false],
["OOM","Cooma",false],
["CPH","Copenhagen",false],
["COR","Cordoba",false],
["ODB","Cordoba",false],
["CDV","Cordova, AK",false],
["CFU","Corfu",false],
["ORK","Cork",false],
["CRP","Corpus Christi, TX",false],
["COO","Cotonou",false],
["CZM","Cozmel",false],
["CGA","Craig, AK",false],
["CEC","Crescent City, CA",false],
["CGB","Cuiaba",false],
["CUL","Culiacan",false],
["CUR","Curacao",false],
["CWB","Curitiba",false],
["DKR","Dakar",false],
["DLM","Dalaman",false],
["DBY","Dalby",false],
["DLC","Dalian",false],
["DAL","Dallas, Love Field, TX",false],
["DFW","Dallas/Ft. Worth, TX",false],
["DJO","Daloa",false],
["DAM","Damascus, International",false],
["DMM","Dammam, King Fahad Int'l",false],
["DAN","Danville, VA",false],
["DAR","Dar es Salam (Daressalam)",false],
["DRW","Darwin",false],
["DDI","Daydream Island",false],
["DAY","Dayton, OH",false],
["DAB","Daytona Beach, FL",false],
["DEC","Decatur, IL",false],
["YDF","Deer Lake/Corner Brook",false],
["DEL","Delhi, Indira Gandhi",true],
["HAG","Den Haag (The Hague)",false],
["DPS","Denpasar/Bali",false],
["DEN","Denver International Airport, CO",false],
["DSK","Dera Ismail Khan",false],
["DRB","Derby",false],
["EMA","Derby (East Midlands)",false],
["LDY","Derry (Londonderry)",false],
["DSM","Des Moines, IA",false],
["DET","Detroit City, MI",false],
["DTW","Detroit Metropolitan Wayne County Airport, MI",false],
["DTT","Detroit Metropolitan Area, MI",false],
["DVL","Devils Lake, ND",false],
["DPO","Devonport",false],
["DHA","Dhahran",false],
["DAC","Dhaka",false],
["DLG","Dillingham, AK",false],
["DNR","Dinard",false],
["DJE","Djerba",false],
["JIB","Djibouti",false],
["DOH","Doha",false],
["DCS","Doncaster, Robin Hood Int'l Airport",false],
["DGM","Dongguan",false],
["DTM","Dortmund",false],
["DHN","Dothan, AL",false],
["DLA","Douala",false],
["DRS","Dresden",false],
["DXB","Dubai",false],
["DBO","Dubbo",false],
["DUB","Dublin",false],
["DUJ","Dubois, PA",false],
["DBV","Dubrovnik",false],
["DBQ","Dubuque, IA",false],
["DUS","Duesseldorf",false],
["DLH","Duluth, MN/Superior, WI",false],
["DUD","Dunedin",false],
["DKI","Dunk Iceland",false],
["DRO","Durango, CO",false],
["DUR","Durban",false],
["DYU","Dushanbe (Duschanbe)",false],
["DUT","Dutch Harbor, AK",false],
["DYA","Dysart",false],
["DZA","Dzaoudzi",false],
["ELS","East London",false],
["IPC","Easter Island",false],
["EAU","Eau Clarie, WI",false],
["EDI","Edinburgh",false],
["YEA","Edmonton",false],
["YEG","Edmonton, International",false],
["YXD","Edmonton, Municipal",false],
["EGS","Egilsstadir",false],
["EIN","Eindhoven",false],
["ELP","El Paso, TX",false],
["ETH","Elat",false],
["VDA","Elat, Ovula",false],
["EKI","Elkhart, IN",false],
["EKO","Elko, NV",false],
["ELL","Ellisras",false],
["EMY","El Minya",false],
["ELM","Elmira, NY",false],
["ELY","Ely, NV",false],
["EDR","Emerald",false],
["EMD","Emerald",false],
["ENF","Enontekioe",false],
["EBB","Entebbe",false],
["ERF","Erfurt",false],
["ERI","Erie, PA",false],
["EVN","Eriwan (Yerevan, Jerevan)",false],
["EBJ","Esbjerg",false],
["ESC","Escabana, MI",false],
["EPR","Esperance",false],
["EUG","Eugene, OR",false],
["ACV","Eureka, CA",false],
["EVV","Evansville, IN",false],
["EVE","Evenes",false],
["FAI","Fairbanks, AK",false],
["LYP","Faisalabad",false],
["FAR","Fargo, ND, MN",false],
["FMN","Farmington, NM",false],
["FAO","Faro",false],
["FAE","Faroer",false],
["FYV","Fayetteville, AR",false],
["FAY","Fayetteville/Ft. Bragg, NC",false],
["FEZ","Fes",false],
["FSC","Figari",false],
["FLG","Flagstaff, AZ",false],
["YFO","Flin Flon",false],
["FNT","Flint, MI",false],
["FLR","Florence",false],
["FLO","Florence, SC",false],
["FLN","Florianopolis",false],
["FRO","Floro",false],
["YFA","Fort Albert",false],
["FDF","Fort de France",false],
["FOD","Fort Dodge, IA",false],
["FHU","Fort Huachuca/Sierra Vista, AZ",false],
["FLL","Fort Lauderdale/Hollywood, FL",false],
["YMM","Fort McMurray",false],
["FMY","Fort Myers, Metropolitan Area, FL",false],
["RSW","Fort Myers, Southwest Florida Reg, FL",false],
["YSM","Fort Smith",false],
["FSM","Fort Smith, AR",false],
["YXJ","Fort St. John",false],
["VPS","Fort Walton Beach, FL",false],
["FWA","Fort Wayne, IN",false],
["FOR","Fortaleza",false],
["FRW","Francistown",false],
["FRA","Frankfurt/Main Int'l Airport",false],
["HNN","Frankfurt/Hahn",false],
["FKL","Franklin/Oil City, PA",false],
["YFC","Fredericton",false],
["FPO","Freeport",false],
["FNA","Freetown",false],
["FRJ","Frejus",false],
["FAT","Fresno, CA",false],
["FDH","Friedrichshafen",false],
["FUE","Fuerteventura",false],
["FJR","Fujairah, Int'l Airport",false],
["FUK","Fukuoka",false],
["FKS","Fukushima-shi, Fukushima Airport",false],
["FNC","Funchal",false],
["FUT","Futuna",false],
["GBE","Gaborone",false],
["GAD","Gadsden, AL",false],
["GNV","Gainesville, FL",false],
["GWY","Galway",false],
["YQX","Gander",false],
["GOU","Garoua",false],
["GDN","Gdansk",false],
["GEX","Geelong",false],
["GVA","Geneva",false],
["GOA","Genoa",false],
["GRJ","George",false],
["GEO","Georgetown",false],
["GET","Geraldton",false],
["GRO","Gerona",false],
["GIB","Gibraltar",false],
["GCC","Gilette, WY",false],
["GIL","Gilgit",false],
["YGX","Gillam",false],
["GLT","Gladstone",false],
["PIK","Glasgow, Prestwick",false],
["GLA","Glasgow",false],
["GGW","Glasgow, MT",false],
["GDV","Glendive, MT",false],
["GOI","Goa",false],
["GYN","Goiania",false],
["OOL","Gold Coast",false],
["GOO","Goondiwindi",false],
["YYR","Goose Bay",false],
["GOZ","Gorna",false],
["GOT","Goteborg",false],
["GOV","Gove (Nhulunbuy)",false],
["GHB","Govenors Harbour",false],
["GRX","Granada",false],
["GBI","Grand Bahama",false],
["GCN","Grand Canyon, AZ",false],
["GCM","Grand Cayman",false],
["GFK","Grand Forks, ND",false],
["GJT","Grand Junction, CO",false],
["GRR","Grand Rapids, MI",false],
["GPZ","Grand Rapids, MN",false],
["GRZ","Graz",false],
["GTF","Great Falls, MT",false],
["GKL","Great Keppel Island",false],
["GRB","Green Bay, WI",false],
["LWB","Greenbrier/Lewisburg, WV",false],
["GSO","Greensboro/Winston Salem, NC",false],
["GLH","Greenville, MS",false],
["PGV","Greenville, NC",false],
["GSP","Greenville/Spartanburg, SC",false],
["GND","Grenada",false],
["GNB","Grenoble",false],
["GFF","Griffith",false],
["GTE","Groote Eyeland",false],
["GTI","Groote Eylandt",false],
["GON","Groton/New London, CT",false],
["GDL","Guadalajara",false],
["GSI","Guadalcanal",false],
["GUM","Guam",false],
["CAN","Guangzhou (Canton) - Baiyun (White Cloud)",false],
["GRU","Guarulhos Int'l - Sao Paulo",false],
["GUA","Guatemala City",false],
["GYE","Guayaquil",false],
["GCI","Guernsey",false],
["GPT","Gulfport/Biloxi, MS",false],
["ULU","Gulu",false],
["GUC","Gunnison/Crested Butte, CO",false],
["GAU","Guwahati",false],
["GWD","Gwadar",false],
["GWE","Gweru",false],
["GYP","Gympie",false],
["HAC","Hachijo Jima",false],
["HFA","Haifa",false],
["HNS","Haines, AK",false],
["HKD","Hakodate",false],
["YHZ","Halifax Int'l",false],
["YUX","Hall Beach",false],
["HAM","Hamburg - Fuhlsbuettel",false],
["HLT","Hamilton",false],
["YHM","Hamilton",false],
["HTI","Hamilton Island",false],
["HFT","Hammerfest",false],
["CMX","Hancock, MI",false],
["HGH","Hangchow (Hangzhou)",false],
["HAJ","Hannover",false],
["HAN","Hanoi - Noibai",false],
["HRE","Harare",false],
["HRB","Harbin (Haerbin)",false],
["HRL","Harlington/South Padre Island, TX",false],
["YHR","Harrington Harbour, PQ",false],
["HAR","Harrisburg, PA - Harrisburg Skyport",false],
["MDT","Harrisburg, PA - Harrisburg Int'l",false],
["BDL","Hartford, CT/Springfield, MA",false],
["HDY","Hatyai (Hat Yai)",false],
["HAU","Haugesund",false],
["HAV","Havana - José Martí Int'l",false],
["HVR","Havre, MT",false],
["HIS","Hayman Island",false],
["HLN","Helena, MT",false],
["JHE","Helsingborg",false],
["HEL","Helsinki - Vantaa",false],
["HER","Heraklion",false],
["HMO","Hermosillo - Gen. Pesqueira Garcia",false],
["HVB","Hervey Bay",false],
["HIB","Hibbing, MN",false],
["HKY","Hickory, NC",false],
["ITO","Hilo, HI",false],
["HHH","Hilton Head Island, SC",false],
["HNK","Hinchinbrook Island",false],
["HIJ","Hiroshima International",false],
["SGN","Ho Chi Minh City (Saigon)",false],
["HBA","Hobart",false],
["HOQ","Hof",false],
["HOG","Holguin",false],
["HMH","Home Hill",false],
["HOM","Homer, AK",false],
["HKG","Hong Kong - Int'l Airport (HKIA)",false],
["ZJK","Hong Kong - Chek Lap Kok",false],
["HIR","Honiara Henderson Int'l",false],
["HNL","Honolulu, HI",false],
["HNH","Hoonah, AK",false],
["HOR","Horta",false],
["HOU","Houston, Hobby, TX",false],
["IAH","Houston, Intercontinental, TX",false],
["HUH","Huahine",false],
["HUX","Huatulco",false],
["HUI","Hue - Phu Bai",false],
["HUY","Humberside",false],
["HTS","Huntington, OH",false],
["HSV","Huntsville, AL",false],
["HRG","Hurghada Int'l",false],
["HON","Huron, SD",false],
["HWN","Hwange National Park",false],
["HYA","Hyannis, MA",false],
["HYG","Hydaburg, AK",false],
["HYD","Hyderabad - Begumpet",true],
["HDD","Hyderabad",false],
["IBZ","Ibiza",false],
["IDA","Idaho Falls, ID",false],
["IGR","Iguazu, Cataratas",false],
["ILP","Ile des Pins",false],
["IOU","Ile Ouen",false],
["ILI","Iliamna, AK",false],
["IPL","Imperial, CA",false],
["IVC","Incercargill",false],
["ICN","Incheon, Incheon Int'l Airport",false],
["IND","Indianapolis, IN",false],
["IGH","Ingham",false],
["IFL","Innisfail",false],
["INN","Innsbruck - Kranebitten",false],
["INL","International Falls, MN",false],
["YEV","Inuvik",false],
["IVC","Invercargill",false],
["INV","Inverness",false],
["IYK","Inykern, CA",false],
["YFB","Iqaluit (Frobisher Bay)",false],
["IQT","Iquitos",false],
["IKT","Irkutsk",false],
["LSG","Ishigaki",false],
["ISB","Islamabad - Islamabad Int'l",false],
["IOM","Isle of Man",false],
["IST","Istanbul - Ataturk",false],
["ITH","Ithaca/Cortland, NY",false],
["IVL","Ivalo",false],
["ZIH","Ixtapa/Zihuatenejo",false],
["IZM","Izmir",false],
["JAC","Jackson Hole, WY",false],
["JXN","Jackson, MI",false],
["JAN","Jackson, MS",false],
["MKL","Jackson, TN",false],
["JAX","Jacksonville, FL",false],
["OAJ","Jacksonville, NC",false],
["JAG","Jacobabad",false],
["JAI","Jaipur - Sanganeer",false],
["HLP","Jakarta - Halim Perdanakusma",false],
["JKT","Jakarta - Kemayoran",false],
["CGK","Jakarta - Soekarno-Hatta",false],
["JLR","Jalandhar",false],
["JMS","Jamestown, ND",false],
["JHW","Jamestown, NY",false],
["IXW","Jamshedpur - Sonari",false],
["JED","Jeddah - King Abdulaziz Int'l",false],
["XRY","Jerez de la Frontera/Cadiz",false],
["JER","Jersey",false],
["JRS","Jerusalem",false],
["TNA","Jinan",false],
["JIW","Jiwani",false],
["JCB","Joacaba",false],
["JPA","Joao Pessoa - Castro Pinto",false],
["JKG","Joenkoeping",false],
["JOE","Joensuu",false],
["JNB","Johannesburg - Johannesburg Int'l",false],
["JST","Johnstown, PA",false],
["JHB","Johore Bahru",false],
["JLN","Joplin, MO",false],
["GJN","Jounieh",false],
["JNU","Juneau, AK - Juneau Int'l",false],
["JYV","Jyvaeskylae",false],
["KBL","Kabul - Khwaja Rawash",false],
["KOJ","Kagoshima",false],
["OGG","Kahului, HI",false],
["KAJ","Kajaani",false],
["KLX","Kalamata",false],
["AZO","Kalamazoo/Battle Creek, MI",false],
["KGI","Kalgoorlie",false],
["FCA","Kalispell, MT",false],
["KLR","Kalmar",false],
["KAN","Kano",false],
["MUE","Kamuela, HI",false],
["QJU","Kanpur",false],
["MCI","Kansas City, MO - Int'l",false],
["KHH","Kaohsiung Int'l",false],
["JHM","Kapalua West, HI",false],
["KHI","Karachi - Quaid-E-Azam Int'l",false],
["FKB","Karlsruhe-Baden - Soellingen",false],
["KSD","Karlstad",false],
["AOK","Karpathos",false],
["KTA","Karratha",false],
["KRB","Karumba",false],
["KRP","Karup",false],
["ZKE","Kaschechawan, PQ",false],
["KSL","Kassala",false],
["KTR","Katherine",false],
["KTM","Kathmandu - Tribhuvan",false],
["MPA","Katima Mulilo/Mpacha",false],
["KHJ","Kauhajoki",false],
["MKK","Kaunakakai, HI",false],
["KVA","Kavalla",false],
["KZN","Kazan (Ka San)",false],
["KMP","Keetmanshoop",false],
["YLW","Kelowna, BC",false],
["KEM","Kemi/Tornio",false],
["ZNS","Kempten",false],
["ENA","Kenai, AK",false],
["KIR","Kerry County",false],
["KTN","Ketchikan, AK",false],
["EYW","Key West, FL",false],
["AHB","Khamis Mushayat",false],
["UVL","Kharga - New Valley",false],
["KRT","Khartoum",false],
["KDD","Khuzdar",false],
["KEL","Kiel - Holtenau",false],
["KBP","Kiev - Borispol",false],
["IEV","Kiev - Zhulhany",false],
["KGL","Kigali - Gregoire Kayibanda",false],
["JRO","Kilimadjaro",false],
["ILE","Killeem, TX",false],
["KIM","Kimberley",false],
["KNS","King Island",false],
["AKN","King Salomon, AK",false],
["KGC","Kingscote",false],
["KIN","Kingston - Norman Manley",false],
["ISO","Kingston, NC",false],
["FIH","Kinshasa - N'Djili",false],
["KKN","Kirkenes",false],
["KIK","Kirkuk",false],
["KRN","Kiruna",false],
["FKI","Kisangani",false],
["KTT","Kittilä",false],
["KIW","Kitwe",false],
["KLU","Klagenfurt",false],
["LMT","Klamath Fall, OR",false],
["KLW","Klawock, AK",false],
["KLZ","Kleinsee",false],
["NOC","Knock",false],
["TYS","Knoxville, TN",false],
["UKB","Kobe",false],
["KCZ","Kochi",false],
["CGN","Köln, Köln/Bonn",false],
["ADQ","Kodiak, AK",false],
["OHT","Kohat",false],
["KOK","Kokkola/Pietarsaari",false],
["CCU","Kolkata (Calcutta) - Netaji Subhas Chandra",false],
["KOA","Kona, HI",false],
["HGO","Korhogo",false],
["KGS","Kos",false],
["BKI","Kota Kinabalu",false],
["OTZ","Kotzbue, AK",false],
["KWM","Kowanyama",false],
["KRK","Krakau",false],
["KRS","Kristiansand",false],
["KID","Kristianstad",false],
["KSU","Kristiansund",false],
["KUB","Kuala Belait",false],
["KUL","Kuala Lumpur - Int'l Airport",false],
["SZB","Kuala Lumpur - Sultan Abdul Aziz Shah",false],
["KUA","Kuantan",false],
["KCH","Kuching",false],
["KMJ","Kumamoto",false],
["KNX","Kununurra",false],
["KUO","Kuopio",false],
["KUH","Kushiro",false],
["YVP","Kuujjuaq (FortChimo)",false],
["YGW","Kuujjuarapik",false],
["KAO","Kuusamo",false],
["KWI","Kuwait - Kuwait Int'l",false],
["UKY","Kyoto",false],
["LEK","Labe",false],
["WLB","Labouchere Bay, AK",false],
["LBU","Labuan",false],
["XLB","Lac Brochet, MB",false],
["LCG","La Coruna",false],
["LSE","La Crosse, WI",false],
["LAE","Lae",false],
["LRH","La Rochelle",false],
["LAF","Lafayette, IN",false],
["LFT","Lafayette, La",false],
["LOS","Lagos - Murtala Muhammed",false],
["YGL","La Grande",false],
["LHE","Lahore",false],
["LCH","Lake Charles, La",false],
["HII","Lake Havasu City, AZ",false],
["TVL","Lake Tahoe, CA",false],
["LKL","Lakselv",false],
["LBQ","Lambarene",false],
["SUF","Lamezia Terme",false],
["LMP","Lampedusa",false],
["LNY","Lanai City, HI",false],
["LNS","Lancaster, PA",false],
["LGK","Langkawi",false],
["LAI","Lannion",false],
["HLA","Lanseria",false],
["LAN","Lansing, MI",false],
["LPB","La Paz - El Alto",false],
["LAP","La Paz - Leon",false],
["LPP","Lappeenranta",false],
["LAR","Laramie, WY",false],
["LRD","Laredo, TX",false],
["LCA","Larnaca",false],
["LPA","Las Palmas",false],
["LAS","Las Vegas, NV",false],
["LBE","Latrobe, PA",false],
["LST","Launceston",false],
["PIB","Laurel/Hattisburg, MS",false],
["LVO","Laverton",false],
["LAW","Lawton, OK",false],
["LZC","Lazaro Cardenas",false],
["YLR","Leaf Rapids",false],
["LEA","Learmouth (Exmouth)",false],
["LEB","Lebanon, NH",false],
["LBA","Leeds/Bradford",false],
["LER","Leinster",false],
["LEJ","Leipzig",false],
["LEY","Lelystad",false],
["BJX","Leon",false],
["LNO","Leonora",false],
["LWS","Lewiston, ID",false],
["LWT","Lewistown, MT",false],
["LEX","Lexington, KY",false],
["LBV","Libreville",false],
["LDK","Lidkoeping",false],
["LGG","Liege",false],
["LIF","Lifou",false],
["LIH","Lihue, HI",false],
["LIL","Lille",false],
["LLW","Lilongwe - Lilongwe International",false],
["LIM","Lima - J Chavez Int'l",false],
["QLI","Limassol",false],
["LIG","Limoges",false],
["LNK","Lincoln, NE",false],
["LDC","Lindeman Island",false],
["LNZ","Linz - Hoersching",false],
["LIQ","Lisala",false],
["LIS","Lisbon - Lisboa",false],
["LSY","Lismore",false],
["LIT","Little Rock, AR",false],
["LPL","Liverpool",false],
["LZR","Lizard Island",false],
["LJU","Ljubljana - Brnik",false],
["IRG","Lockhart River",false],
["LFW","Lome",false],
["YXU","London",false],
["LON","London",false],
["LCY","London - City Airport",false],
["LGW","London - Gatwick",false],
["LHR","London - Heathrow",false],
["LTN","London - Luton",false],
["STN","London - Stansted",false],
["LGB","Long Beach, CA",false],
["LIJ","Long Island, AK",false],
["ISP","Long Island, Islip, NY - Mac Arthur",false],
["LRE","Longreach",false],
["GGG","Longview/Kilgore, TX",false],
["LYR","Longyearbyen - Svalbard",false],
["LTO","Loreto",false],
["LRT","Lorient",false],
["LAX","Los Angeles, CA - Int'l",false],
["SJD","Los Cabos",false],
["LMM","Los Mochis",false],
["TFN","Los Rodeos",false],
["LSZ","(Mali) Losinj - Losinj Arpt",false],
["LDE","Lourdes/Tarbes",false],
["SDF","Louisville, KY",false],
["LAD","Luanda - 4 de Fevereiro",false],
["LBB","Lubbock, TX",false],
["LKO","Lucknow",false],
["LUD","Luederitz",false],
["MLA","Luga",false],
["LUG","Lugano",false],
["LLA","Lulea",false],
["FBM","Lumbumbashi",false],
["LUN","Lusaka",false],
["LUJ","Lusisiki",false],
["LUX","Luxembourg",false],
["LXR","Luxor",false],
["LWO","Lvov (Lwow, Lemberg)",false],
["LYH","Lynchburg, VA",false],
["LYS","Lyon",false],
["MST","Maastricht/Aachen",false],
["MCP","Macapa",false],
["MFM","Macau",false],
["MCZ","Maceio",false],
["MKY","Mackay",false],
["MCN","Macon, GA",false],
["NOP","Mactan Island - Nab",false],
["MED","Madinah, Mohammad Bin Abdulaziz",false],
["MSN","Madison, WI",false],
["MAD","Madrid - Barajas",false],
["SEZ","Mahe - Seychelles Int'l",false],
["MAH","Mahon",false],
["MTL","Maitland",false],
["MJN","Majunga",false],
["MZG","Makung",false],
["SSG","Malabo",false],
["AGP","Malaga",false],
["MLE","Male - International",false],
["MYD","Malindi",false],
["MMA","Malmo (Malmoe)",false],
["MMX","Malmo (Malmoe) - Sturup",false],
["MJC","Man",false],
["MGA","Managua - Augusto C Sandino",false],
["MAO","Manaus",false],
["MAN","Manchester",false],
["MHT","Manchester, NH",false],
["MFO","Manguna",false],
["XMH","Manihi",false],
["MNL","Manila - Ninoy Aquino Int'l",false],
["ZLO","Manzanillo",false],
["MTS","Manzini - Matsapha Int'l",false],
["MPM","Maputo - Maputo International",false],
["MDQ","Mar del Plata",false],
["MAR","Maracaibo - La Chinita",false],
["MFQ","Maradi",false],
["MTH","Marathon, FL",false],
["MEE","Mare",false],
["MGH","Margate",false],
["PMV","Margerita",false],
["MBX","Maribor",false],
["MHQ","Mariehamn (Maarianhamina)",false],
["MVR","Maroua",false],
["MQT","Marquette, MI",false],
["RAK","Marrakech - Menara",false],
["MUH","Marsa Matrah (Marsa Matruh)",false],
["MRS","Marseille",false],
["MHH","Marsh Harbour",false],
["MVY","Martha's Vineyard, MA",false],
["MBH","Maryborough",false],
["MSU","Maseru - Moshoeshoe Int'l",false],
["MCW","Mason City, IA",false],
["MVZ","Masvingo",false],
["MMJ","Matsumoto, Nagano",false],
["MYJ","Matsuyama",false],
["MTO","Mattoon, IL",false],
["MUB","Maun",false],
["MAU","Maupiti",false],
["MRU","Mauritius - S.Seewoosagur Ram Int'l",false],
["MAZ","Mayaguez",false],
["MZT","Mazatlan",false],
["MFE","McAllen, TX",false],
["MES","Medan",false],
["MDE","Medellin",false],
["MFR","Medford, OR",false],
["MED","Medina",false],
["MKR","Meekatharra",false],
["MEL","Melbourne - Tullamarine",false],
["MLB","Melbourne, FL",false],
["MEM","Memphis, TN",false],
["MDZ","Mendoza",false],
["MDC","Manado",false],
["MCE","Merced, CA",false],
["MID","Merida",false],
["MEI","Meridian, MS",false],
["MIM","Merimbula",false],
["MEZ","Messina",false],
["MTM","Metlakatla, AK",false],
["MZM","Metz",false],
["MXL","Mexicali",false],
["MEX","Mexico City",false],
["MEX","Mexico City - Juarez International",false],
["MFU","Mfuwe",false],
["MIA","Miami, FL",false],
["MWD","Mianwali",false],
["MMM","Middlemount",false],
["MAF","Midland/Odessa, TX",false],
["MIK","Mikkeli",false],
["MIL","Milan",false],
["LIN","Milan - Linate",false],
["MXP","Milan - Malpensa",false],
["BGY","Milan - Orio Al Serio",false],
["MQL","Mildura",false],
["MLS","Miles City, MT",false],
["MFN","Milford Sound",false],
["MKE","Milwaukee, WI",false],
["MTT","Minatitlan",false],
["MRV","Mineralnye Vody",false],
["MSP","Minneapolis - St. Paul Int'l Airport, MN",false],
["MOT","Minot, ND",false],
["MSQ","Minsk, International",false],
["MYY","Miri",false],
["QML","Mirpur",false],
["MSO","Missula, MT",false],
["MHE","Mitchell, SD",false],
["MMY","Miyako Jima (Ryuku Islands) - Hirara",false],
["MBM","Mkambati",false],
["MFF","Moanda",false],
["MOB","Mobile, AL - Pascagoula, MS",false],
["MOD","Modesto, CA",false],
["MJD","Moenjodaro",false],
["MGQ","Mogadischu",false],
["OKU","Mokuti",false],
["MLI","Moline/Quad Cities, IL",false],
["MBA","Mombasa - Moi International",false],
["MIR","Monastir",false],
["YQM","Moncton",false],
["MLU","Monroe, La",false],
["MLW","Monrovia",false],
["ROB","Monrovia - Roberts Int'l",false],
["MBJ","Montenego Bay",false],
["QGF","Montenegro",false],
["MRY","Monterey, CA",false],
["MTY","Monterrey",false],
["NTR","Monterrey - Aeropuerto Del Norte",false],
["MVD","Montevideo - Carrasco",false],
["MGM","Montgomery, AL",false],
["MPL","Montpellier - Frejorgues",false],
["YMQ","Montreal",false],
["YUL","Montreal - Dorval (Montréal-Trudeau)",false],
["YMX","Montreal - Mirabel",false],
["MTJ","Montrose/Tellruide, CO",false],
["MOZ","Moorea",false],
["MOV","Moranbah",false],
["MRZ","Moree",false],
["MLM","Morelia",false],
["MGW","Morgantown, WV",false],
["HNA","Morioka, Hanamaki",false],
["HAH","Moroni - Prince Said Ibrahim",false],
["YVA","Moroni - Iconi",false],
["MOW","Moscow - Metropolitan Area",false],
["DME","Moscow - Domodedovo",false],
["SVO","Moscow - Sheremetyevo",false],
["VKO","Moscow - Vnukovo",false],
["MWH","Moses Lake, WA",false],
["OMO","Mostar",false],
["OSM","Mosul",false],
["MJL","Mouila",false],
["MQQ","Moundou",false],
["GTN","Mount Cook",false],
["MGB","Mount Gambier",false],
["MMG","Mount Magnet",false],
["ISA","Mt. Isa",false],
["MCL","Mt. McKinley, AK",false],
["MUC","Muenchen (Munich) - Franz Josef Strauss",false],
["FMO","Muenster/Osnabrueck",false],
["MSR","Muenster/Osnabrueck",false],
["MLH","Mulhouse",false],
["MUX","Multan",false],
["MJV","Murcia",false],
["MMK","Murmansk",false],
["MCT","Muscat - Seeb",false],
["MSL","Muscle Shoals, AL",false],
["MKG","Muskegon, MI",false],
["MFG","Muzaffarabad",false],
["MVB","Mvengue",false],
["JMK","Mykonos",false],
["MYR","Myrtle Beach, SC",false],
["KMI","Miyazaki",false],
["MJT","Mytilene (Lesbos)",false],
["MZF","Mzamba",false],
["NAN","Nadi",false],
["NGS","Nagasaki",false],
["NGO","Nagoya - Komaki AFB",false],
["NAG","Nagpur",false],
["NBO","Nairobi",false],
["ENC","Nancy",false],
["YSR","Nanisivik",false],
["NNG","Nanning",false],
["NTE","Nantes",false],
["ACK","Nantucket, MA",false],
["NAP","Naples",false],
["APF","Naples, FL",false],
["NAA","Narrabri",false],
["NRA","Narrandera",false],
["UAK","Narsarsuaq",false],
["BNA","Nashville, TN",false],
["NAS","Nassau",false],
["NAT","Natal",false],
["SUV","Nausori",false],
["WNS","Nawab Shah",false],
["NDJ","N'Djamena",false],
["NLA","N'Dola",false],
["NSN","Nelson",false],
["NLP","Nelspruit",false],
["MQP","Nelspruit - Kruger Mpumalanga Int'l Airport",false],
["NEV","Nevis",false],
["EWN","New Bern, NC",false],
["HVN","New Haven, CT",false],
["MSY","New Orleans, La",false],
["UVL","New Valley - Kharga",false],
["JFK","New York - John F. Kennedy, NY",false],
["LGA","New York - La Guardia, NY",false],
["EWR","New York - Newark, NJ",false],
["NYC","New York, NY",false],
["SWF","Newburgh, NY",false],
["BEO","Newcastle - Belmont",false],
["NTL","Newcastle - Williamtown",false],
["NCL","Newcastle",false],
["NCS","Newcastle",false],
["ZNE","Newman",false],
["PHF","Newport News/Williamsburg, VA",false],
["NGE","N'Gaoundere",false],
["IAG","Niagara Falls Int'l",false],
["NIM","Niamey",false],
["NCE","Nice - Cote D'Azur",false],
["NIC","Nicosia",false],
["NLV","Nikolaev",false],
["KIJ","Niigata",false],
["FNI","Nimes",false],
["INI","Nis",false],
["OME","Nome, AK",false],
["NSA","Noosa",false],
["NLK","Norfolk Island",false],
["ORF","Norfolk/Virginia Beach, VA",false],
["YVQ","Norman Wells",false],
["NRK","Norrkoeping",false],
["OTH","North Bend, OR",false],
["ELH","North Eleuthera",false],
["NDB","Nouadhibou",false],
["NKC","Nouakchott",false],
["NOU","Noumea",false],
["QND","Novi Sad",false],
["OVB","Novosibirsk - Tolmachevo",false],
["NUE","Nürnberg (Nuremberg)",false],
["NLD","Nuevo Laredo",false],
["TBU","Nuku'alofa - Fua'Amotu International",false],
["OAK","Oakland, CA",false],
["OAX","Oaxaca",false],
["ODE","Odense",false],
["ODS","Odessa",false],
["ORB","Oerebro",false],
["OHD","Ohrid",false],
["OIT","Oita",false],
["OKJ","Okayama",false],
["OKA","Okinawa, Ryukyo Island - Naha",false],
["OKC","Oklahoma City, OK - Will Rogers World",false],
["OLB","Olbia",false],
["OLP","Olympic Dam",false],
["OMA","Omaha, NE",false],
["OND","Ondangwa",false],
["ONT","Ontario, CA",false],
["ORN","Oran (Ouahran)",false],
["OAG","Orange",false],
["SNA","Orange County (Santa Ana), CA",false],
["OMD","Oranjemund",false],
["KOI","Orkney",false],
["ORL","Orlando Metropolitan Area, FL",false],
["ORL","Orlando Int'l Airport, FL",false],
["ORS","Orpheus Island",false],
["OSA","Osaka, Metropolitan Area",false],
["ITM","Osaka - Itami",false],
["KIX","Osaka - Kansai Int'l Airport",false],
["OSH","Oshkosh, WI",false],
["OSI","Osijek",false],
["OSL","Oslo",false],
["FBU","Oslo - Fornebu",false],
["TRF","Oslo - Sandefjord",false],
["YOW","Ottawa - Hull",false],
["ODA","Ouadda",false],
["OZZ","Ouarzazate",false],
["OUH","Oudtshoorn",false],
["OUA","Ouagadougou",false],
["OUD","Oujda",false],
["OUL","Oulu",false],
["OVD","Oviedo",false],
["OWB","Owensboro, KY",false],
["OXR","Oxnard, CA",false],
["UVE","Oyem",false],
["PAD","Paderborn/Lippstadt",false],
["PAH","Paducah, KY",false],
["PGA","Page/Lake Powell, AZ",false],
["PPG","Pago Pago",false],
["PKB","Pakersburg, WV/Marietta, OH",false],
["PMO","Palermo - Punta Raisi",false],
["PSP","Palm Springs, CA",false],
["PMI","Palma de Mallorca",false],
["PMD","Palmdale/Lancaster, CA",false],
["PMR","Palmerston North",false],
["PTY","Panama City - Tocumen International",false],
["PFN","Panama City, FL",false],
["PJG","Panjgur",false],
["PNL","Pantelleria",false],
["PPT","Papeete - Faaa",false],
["PFO","Paphos",false],
["PBO","Paraburdoo",false],
["PBM","Paramaribo - Zanderij Int'l",false],
["PAR","Paris",false],
["CDG","Paris - Charles de Gaulle",false],
["LBG","Paris - Le Bourget",false],
["ORY","Paris - Orly",false],
["PBH","Paro",false],
["PSC","Pasco, WA",false],
["PSI","Pasni",false],
["PAT","Patna",false],
["PYX","Pattaya",false],
["PUF","Pau",false],
["PLN","Pellston, MI",false],
["PEN","Penang International",false],
["PDT","Pendelton, OR",false],
["PNS","Pensacola, FL",false],
["PIA","Peoria/Bloomington, IL",false],
["PEI","Pereira",false],
["PGF","Perpignan",false],
["PER","Perth Int'l",false],
["PEG","Perugia",false],
["PSR","Pescara",false],
["PEW","Peshawar",false],
["PSG","Petersburg, AK",false],
["PHW","Phalaborwa",false],
["PHL","Philadelphia, PA - Int'l",false],
["PNH","Phnom Penh - Pochentong",false],
["PHX","Phoenix, AZ - Sky Harbor Int'l",false],
["HKT","Phuket",false],
["PIR","Pierre, SD",false],
["PZB","Pietermaritzburg",false],
["PTG","Pietersburg",false],
["NTY","Pilanesberg/Sun City",false],
["PSA","Pisa - Gal Galilei",false],
["PIT","Pittsburgh Int'l Airport, PA",false],
["PLB","Plattsburgh, NY",false],
["PBZ","Plettenberg Bay",false],
["PIH","Pocatello, ID",false],
["TGD","Podgorica",false],
["PNI","Pohnpei",false],
["PTP","Pointe a Pitre",false],
["PNR","Pointe Noire",false],
["PSE","Ponce",false],
["PDL","Ponta Delgada",false],
["POR","Pori",false],
["CLM","Port Angeles, WA",false],
["PAP","Port au Prince",false],
["PUG","Port Augusta",false],
["PLZ","Port Elizabeth",false],
["POG","Port Gentil",false],
["PHC","Port Harcourt",false],
["PHE","Port Hedland",false],
["PTJ","Portland",false],
["PWM","Portland, ME",false],
["PDX","Portland Int'l, OR",false],
["PLO","Port Lincoln",false],
["PQQ","Port Macquarie",false],
["YPN","Port Menier, PQ",false],
["POM","Port Moresby - Jackson Field",false],
["OPO","Porto",false],
["POA","Porto Alegre",false],
["POS","Port of Spain",false],
["PSD","Port Said",false],
["PXO","Porto Santo",false],
["PVH","Porto Velho",false],
["VLI","Port Vila",false],
["POU","Poughkeepsie, NY",false],
["POZ","Poznan, Lawica",false],
["PRG","Prague - Ruzyne",false],
["RAI","Praia",false],
["PQI","Presque Island, ME",false],
["PRY","Pretoria - Wonderboom Apt.",false],
["PVK","Preveza/Lefkas",false],
["YXS","Prince George",false],
["YPR","Prince Rupert/Digby Island",false],
["PRN","Pristina",false],
["PPP","Prosperpine",false],
["PVD","Providence, RI",false],
["SCC","Prudhoe Bay, AK",false],
["PBC","Puebla",false],
["PUB","Pueblo, CO",false],
["PXM","Puerto Escondido",false],
["PZO","Puerto Ordaz",false],
["POP","Puerto Plata",false],
["PVR","Puerto Vallarta",false],
["XPK","Pukatawagan",false],
["PUY","Pula",false],
["PUW","Pullman, WA",false],
["PNQ","Pune",false],
["PUQ","Punta Arenas",false],
["PUJ","Punta Cana",false],
["PUS","Pu San (Pusan) - Kimhae",false],
["FNJ","Pyongyang - Sunan",false],
["YQB","Quebec - Quebec Int'l",false],
["UEE","Queenstown",false],
["ZQN","Queenstown",false],
["UET","Quetta",false],
["TAO","Qingdao",false],
["UIP","Quimper",false],
["UIN","Quincy, IL",false],
["UIO","Quito - Mariscal Sucr",false],
["RBA","Rabat - Sale",false],
["RYK","Rahim Yar Khan",false],
["RFP","Raiatea",false],
["YOP","Rainbow Lake, AB",false],
["RAJ","Rajkot",false],
["RDU","Raleigh/Durham, NC",false],
["IXR","Ranchi",false],
["RGI","Rangiroa",false],
["RGN","Rangoon (Yangon) - Mingaladon",false],
["RAP","Rapid City, SD",false],
["RAR","Rarotonga Cook",false],
["RKT","Ras al Khaymah (Ras al Khaimah)",false],
["RAZ","Rawala Kot",false],
["RWP","Rawalpindi",false],
["RDG","Reading, PA",false],
["REC","Recife",false],
["RDD","Redding, CA",false],
["RDM","Redmond, OR",false],
["REG","Reggio Calabria",false],
["YQR","Regina",false],
["TFS","Reina Sofia",false],
["RNS","Rennes",false],
["RNO","Reno, NV",false],
["YRB","Resolute Bay",false],
["REU","Reus",false],
["REK","Reykjavik - Metropolitan Area",false],
["KEF","Reykjavik - Keflavik International",false],
["RHI","Rhinelander, WI",false],
["RHO","Rhodos",false],
["RCB","Richards Bay",false],
["RIC","Richmond, VA",false],
["RIX","Riga",false],
["RJK","Rijeka",false],
["RMI","Rimini",false],
["RBR","Rio Branco",false],
["GIG","Rio de Janeiro - Galeao",false],
["SDU","Rio de Janeiro - Santos Dumont",false],
["RIO","Rio de Janeiro",false],
["RUH","Riyadh - King Khaled Int'l",false],
["RNE","Roanne",false],
["ROA","Roanoke, VA",false],
["RTB","Roatan",false],
["RST","Rochester, MN",false],
["ROC","Rochester, NY",false],
["RSD","Rock Sound",false],
["RKS","Rock Springs, WY",false],
["RFD","Rockford, IL",false],
["ROK","Rockhampton",false],
["RKD","Rockland, ME",false],
["RWI","Rocky Mount - Wilson, NC",false],
["RDZ","Rodez",false],
["RRG","Rodrigues Island",false],
["RNN","Roenne",false],
["ROM","Rome",false],
["CIA","Rome - Ciampino",false],
["FCO","Rome - Fuimicino",false],
["RNB","Ronneby",false],
["ROS","Rosario",false],
["ROT","Rotorua",false],
["RTM","Rotterdam",false],
["RVN","Rovaniemi",false],
["NDU","Rundu",false],
["ROU","Ruse",false],
["SCN","Saarbruecken",false],
["SMF","Sacramento, CA",false],
["SDS","Sado Shima",false],
["MBS","Saginaw/Bay City/Midland, MI",false],
["SDT","Saidu Sharif",false],
["SGN","Saigon (Ho Chi Minh City)",false],
["SBK","Saint Brieuc",false],
["RUN","Saint Denis de la Reunion",false],
["YSJ","Saint John",false],
["SPN","Saipan",false],
["SID","Sal",false],
["SLL","Salalah",false],
["SLE","Salem, OR",false],
["SNS","Salinas, CA",false],
["SNC","Salinas",false],
["SAY","Salisbury",false],
["SBY","Salisbury, MD",false],
["SKG","Saloniki",false],
["SLA","Salta, Gen Belgrano",false],
["SLC","Salt Lake City, UT",false],
["SSA","Salvador",false],
["SZG","Salzburg - W.A. Mozart",false],
["SKD","Samarkand",false],
["SMI","Samos",false],
["ADZ","San Andres",false],
["SJT","San Angelo, TX",false],
["SAT","San Antonio, TX",false],
["BRC","San Carlos de Bariloche",false],
["SAN","San Diego - Lindberg Field Int'l, CA",false],
["SFO","San Francisco - Int'l Airport, SA",false],
["SJD","San Jose Cabo",false],
["SJO","San Jose",false],
["SJC","San Jose, CA",false],
["SJU","San Juan Perto",false],
["SBP","San Luis Obisco, CA",false],
["SLP","San Luis Potosi",false],
["SPY","San Pedro",false],
["SAP","San Pedro Sula",false],
["ZSA","San Salvador",false],
["SAL","San Salvador",false],
["EAS","San Sebastian",false],
["SAH","Sanaa (Sana'a) - Sana'a International",false],
["YZP","Sandspit",false],
["SBA","Santa Barbara, CA",false],
["SPC","Santa Cruz de la Palma",false],
["SRZ","Santa Cruz de la Sierra",false],
["SKV","Santa Katarina - Mount Sinai",false],
["SMA","Santa Maria",false],
["SMX","Santa Maria, CA",false],
["SDR","Santander",false],
["STS","Santa Rosa, CA",false],
["SRB","Santa Rosa",false],
["SRA","Santa Rosa",false],
["RSA","Santa Rosa",false],
["SDH","Santa Rosa Copan",false],
["SSL","Santa Rosalia",false],
["SRL","Santa Rosalia",false],
["SCU","Santiago - Antonio Maceo Airport",false],
["SCL","Santiago de Chile - Arturo Merino Benitez",false],
["SCQ","Santiago de Compostela",false],
["SON","Santo",false],
["SDQ","Santo Domingo",false],
["SLZ","Sao Luis",false],
["SAO","Sao Paulo",false],
["CGH","Sao Paulo - Congonhas",false],
["GRU","Sao Paulo - Guarulhos",false],
["VCP","Sao Paulo - Viracopos",false],
["TMS","Sao Tome",false],
["SPK","Sapporo",false],
["OKD","Sapporo - Okadama",false],
["CTS","Sapporo - Shin-Chitose Airport",false],
["SJJ","Sarajevo",false],
["SRQ","Sarasota/Bradenton, FL",false],
["YXE","Saskatoon",false],
["ZSS","Sassandra",false],
["SAV","Savannah, GA",false],
["SVL","Savonlinna",false],
["NSO","Scone",false],
["SCF","Scottsdale, AZ",false],
["SEA","Seattle/Tacoma, WA",false],
["SEB","Sehba",false],
["SJY","Seinaejoki",false],
["PKW","Selibi Phikwe",false],
["SDJ","Sendai",false],
["ICN","Seoul - Incheon Int'l Airport",false],
["SEL","Seoul - Kimpo",false],
["SVQ","Sevilla",false],
["SFA","Sfax",false],
["ZTM","Shamattawa, MB",false],
["SHA","Shanghai - Hongqiao",false],
["PVG","Shanghai - Pu Dong",false],
["SNN","Shannon (Limerick)",false],
["SHJ","Sharjah",false],
["SSH","Sharm El Sheikh",false],
["SZD","Sheffield, City Airport",false],
["DCS","Sheffield, Doncaster, Robin Hood Int'l Airport",false],
["SHD","Shenandoah Valley/Stauton, VA",false],
["SHE","Shenyang",false],
["SZX","Shenzhen",false],
["SHR","Sheridan, WY",false],
["SHV","Shreveport, La",false],
["JHQ","Shute Harbour",false],
["SBW","Sibu",false],
["SDY","Sidney, MT",false],
["SLS","Silistra",false],
["SIP","Simferopol",false],
["MPD","Sindhri",false],
["QPG","Singapore - Paya Lebar",false],
["SIN","Singapore - Changi",false],
["SIX","Singleton",false],
["SUX","Sioux City, IA",false],
["FSD","Sioux Falls, SD",false],
["SIS","Sishen",false],
["SIT","Sitka, AK",false],
["SEW","Siwa",false],
["SGY","Skagway, AK",false],
["KDU","Skardu",false],
["JSI","Skiathos",false],
["SKP","Skopje",false],
["SKS","Skrydstrup",false],
["SZK","Skukuza",false],
["SXL","Sligo",false],
["YYD","Smithers",false],
["SOT","Sodankylae",false],
["SGD","Soenderborg",false],
["SFJ","Soendre Stroemfjord",false],
["SOF","Sofia - Vrazhdebna",false],
["SOG","Sogndal",false],
["SOU","Southampton - Eastleigh",false],
["SBN","South Bend, IN",false],
["XSI","South Indian Lake, MB",false],
["SOI","South Molle Island",false],
["SEN","Southend",false],
["SPU","Split",false],
["GEG","Spokane, WA",false],
["SBU","Springbok",false],
["SPI","Springfield, IL",false],
["SGF","Springfield, MO",false],
["SXR","Srinagar",false],
["YIF","St. Augustin, PQ",false],
["STX","St. Croix",false],
["EBU","St. Etienne",false],
["SGU","St. George, UT",false],
["YYT","St. John's",false],
["SKB","St. Kitts",false],
["STL","St. Louis - Lambert, MO",false],
["UVF","St. Lucia Hewanorra",false],
["SLU","St. Lucia Vigle",false],
["SXM","St. Marteen",false],
["SFG","St. Martin",false],
["LED","St. Petersburg (Leningrad) - Pulkovo",false],
["FSP","St. Pierre, NF",false],
["STT","St. Thomas",false],
["SVD","St. Vincent",false],
["STN","Stansted (London)",false],
["SCE","State College/Belefonte, PA",false],
["SVG","Stavanger",false],
["HDN","Steamboat Springs, CO",false],
["SZZ","Stettin",false],
["STO","Stockholm Metropolitan Area",false],
["ARN","Stockholm - Arlanda",false],
["BMA","Stockholm - Bromma",false],
["SCK","Stockton, CA",false],
["SYY","Stornway",false],
["SXB","Strassburg",false],
["KBY","Streaky Bay",false],
["STR","Stuttgart - Echterdingen",false],
["SUL","Sui",false],
["SKZ","Sukkur",false],
["LSI","Sumburgh (Shetland)",false],
["SUN","Sun Valley, ID",false],
["SDL","Sundsvall",false],
["MCY","Sunshine Coast",false],
["SUB","Surabaya - Juanda",false],
["STV","Surat",false],
["SUV","Suva/Nausori",false],
["SWP","Swakopmund",false],
["SYD","Sydney - Kingsford Smith",false],
["ZYL","Sylhet",false],
["SYR","Syracuse, NY",false],
["TUU","Tabuk",false],
["TIF","Taif",false],
["TPE","Taipei - Chiang Kai Shek",false],
["TAY","Taipei - Sung Shan",false],
["TYN","Taiyuan",false],
["TAK","Takamatsu",false],
["TKA","Talkeetna, AK",false],
["TLH","Tallahassee, FL",false],
["QUF","Tallinn - Pirita Harbour",false],
["TLL","Tallinn - Ulemiste",false],
["TPA","Tampa Int'l, FL",false],
["TMP","Tampere",false],
["TAM","Tampico - Gen. F. Javier Mina",false],
["TMW","Tamworth",false],
["TNG","Tanger - Boukhalef",false],
["TRO","Taree",false],
["TGV","Targovishte",false],
["TAS","Tashkent - Vostochny",false],
["TWU","Tawau",false],
["TBS","Tbilisi - Novo Alexeyevka",false],
["TEU","Te Anau",false],
["MME","Teesside, Durham Tees Valley",false],
["TGU","Tegucigalpa",false],
["THR","Tehran (Teheran) - Mehrabad",false],
["TLV","Tel Aviv - Ben Gurion Int'l",false],
["TEX","Telluride, CO",false],
["TEM","Temora",false],
["TCI","Tenerife",false],
["TFS","Tenerife - Sur Reina Sofia",false],
["TFN","Tenerife - Norte Los Rodeos",false],
["TCA","Tennant Creek",false],
["TER","Terceira",false],
["THE","Teresina",false],
["TMZ","Termez (Termes)",false],
["YXT","Terrace",false],
["HUF","Terre Haute, IN",false],
["TXK","Texarkana, AR",false],
["TCU","Thaba'Nchu",false],
["YQD","The Pas",false],
["SKG","Thessaloniki - Makedonia Apt.",false],
["TVF","Thief River Falls, MN",false],
["JTR","Thira",false],
["TRV","Thiruvananthapuram",false],
["TED","Thisted",false],
["YTH","Thompson",false],
["KTB","Thorne Bay, AK",false],
["YQT","Thunder Bay",false],
["TIS","Thursday Island",false],
["TSN","Tianjin",false],
["TIJ","Tijuana - Rodriguez",false],
["TOD","Tioman",false],
["TIA","Tirana - Rinas",false],
["TRZ","Tiruchirapally",false],
["TIV","Tivat",false],
["TAB","Tobago",false],
["TKS","Tokushima",false],
["TYO","Tokyo",false],
["HND","Tokyo - Haneda",false],
["NRT","Tokyo - Narita",false],
["TOL","Toledo, OH",false],
["TPR","Tom Price",false],
["TWB","Toowoomba",false],
["YTZ","Toronto Island",false],
["YYZ","Toronto - Lester B. Pearson",false],
["YTO","Toronto",false],
["EIS","Tortola",false],
["TOU","Touho",false],
["TLS","Toulouse - Blagnac",false],
["TSV","Townsville",false],
["TOY","Toyama",false],
["TPS","Trapani",false],
["TVC","Traverse City, MI",false],
["TCB","Treasure Cay",false],
["TTN","Trenton/Princeton, NJ",false],
["TSF","Treviso",false],
["TRI","Tri-Cities Regional, TN/VA",false],
["TRS","Trieste",false],
["TIP","Tripoli - Tripoli Int'l",false],
["TOS","Tromsoe",false],
["TRD","Trondheim",false],
["TSB","Tsumeb",false],
["TUS","Tucson, AZ",false],
["TUP","Tulepo, MS",false],
["TUL","Tulsa, OK",false],
["TUN","Tunis - Carthage",false],
["TUK","Turbat",false],
["TRN","Turin",false],
["TKU","Turku",false],
["TCL","Tuscaloosa, AL",false],
["TGZ","Tuxtla Gutierrez",false],
["TWF","Twin Falls, ID",false],
["TYR","Tyler, TX",false],
["UDI","Uberlandia, MG",false],
["UPG","Ujung Pandang",false],
["ULN","Ulaanbaatar - Buyant Uhaa",false],
["UUD","Ulan-Ude",false],
["ULD","Ulundi",false],
["UTT","Umtata",false],
["UTN","Upington",false],
["URC","Urumqi",false],
["UTP","Utapao (Pattaya)",false],
["UCA","Utica, NY",false],
["VAA","Vaasa",false],
["VXO","Vaexjoe",false],
["EGE","Vail, CO",false],
["YVO","Val d'Or",false],
["VDZ","Valdez, AK",false],
["VLD","Valdosta, GA",false],
["VLC","Valencia",false],
["VLN","Valencia",false],
["VLL","Valladolid",false],
["VAP","Valparaiso",false],
["VDE","Valverde",false],
["YVR","Vancouver - Vancouver Int'l",false],
["VRA","Varadero",false],
["VNS","Varanasi",false],
["VRK","Varkaus",false],
["VAR","Varna",false],
["VST","Vasteras",false],
["VLU","Velikiye Luki (Welikije Luki)",false],
["VCE","Venice - Marco Polo",false],
["VER","Veracruz",false],
["VEL","Vernal, UT",false],
["VRB","Vero Beach/Ft. Pierce, FL",false],
["VBS","Verona (Brescia) Montichiari",false],
["VRN","Verona",false],
["YYJ","Victoria",false],
["VFA","Victoria Falls",false],
["VID","Vidin",false],
["VTE","Vientiane - Wattay",false],
["VGO","Vigo",false],
["VSA","Villahermosa",false],
["VIJ","Virgin Gorda",false],
["VIS","Visalia, CA",false],
["VBY","Visby",false],
["VIT","Vitoria",false],
["VIX","Vitoria",false],
["VYD","Vryheid",false],
["YWK","Wabush",false],
["ACT","Waco, TX",false],
["WGA","Wagga",false],
["ALW","Walla Walla, WA",false],
["WLS","Wallis",false],
["WVB","Walvis Bay",false],
["WMB","Warrnambool",false],
["WAW","Warsaw",false],
["BWI","Washington DC - Baltimore Washington Int'l",false],
["IAD","Washington DC - Dulles Int'l",false],
["DCA","Washington DC - Ronald Reagan National",false],
["WAS","Washington, DC",false],
["ALO","Waterloo, IA",false],
["ATY","Watertown, SD",false],
["CWA","Wausau/Stevens Point, WI",false],
["WEI","Weipa",false],
["WEL","Welkom",false],
["WLG","Wellington",false],
["EAT","Wenatchee, WA",false],
["PBI","West Palm Beach, FL",false],
["WYS","West Yellowstone, MT",false],
["GWT","Westerland",false],
["WHK","Whakatane",false],
["YXN","Whale Cove, NT",false],
["WRE","Whangarei",false],
["HPN","White Plains, NY",false],
["YXY","Whitehorse",false],
["HAP","Whitsunday Resort",false],
["WYA","Whyalla",false],
["SPS","Wichita Falls, TX",false],
["ICT","Wichita, KS",false],
["WIC","Wick",false],
["WHM","Wickham",false],
["VIE","Wien (Vienna) - Vienna Int'l",false],
["WIE","Wiesbaden, Air Base",false],
["AVP","Wilkes Barre/Scranton, PA",false],
["IPT","Williamsport, PA",false],
["ISL","Williston, ND",false],
["ILM","Wilmington, NC",false],
["VNO","Wilna (Vilnius)",false],
["WUN","Wiluna",false],
["ERS","Windhoek - Eros",false],
["WDH","Windhoek - Hosea Kutako Int'l",false],
["YQG","Windsor Ontario",false],
["YWG","Winnipeg Int'l",false],
["OLF","Wolf Point, MT",false],
["WOL","Wollongong",false],
["UMR","Woomera",false],
["ORH","Worcester, MA",false],
["WRL","Worland, WY",false],
["WRG","Wrangell, AK",false],
["WUH","Wuhan",false],
["WYN","Wyndham",false],
["XMN","Xiamen",false],
["XIY","Xi'an - Xianyang",false],
["YKM","Yakima, WA",false],
["YAK","Yakutat, AK",false],
["YKS","Yakutsk",false],
["GAJ","Yamagata, Junmachi",false],
["ASK","Yamoussoukro",false],
["YNB","Yanbu",false],
["RGN","Yangon (Rangoon) - Mingaladon",false],
["YAO","Yaounde",false],
["YZF","Yellowknife",false],
["YOK","Yokohama",false],
["YUM","Yuma, AZ",false],
["ZCL","Zacatecas",false],
["ZAD","Zadar",false],
["ZAG","Zagreb - Pleso",false],
["ZTH","Zakynthos",false],
["ZAZ","Zaragoza",false],
["PZH","Zhob",false],
["ZND","Zinder",false],
["OUZ","Zouerate",false],
["ZRH","Zurich (Zürich) - Kloten",false]
				];
				/*var cities = [
					["BOM","Mumbai",true],
					["DEL","New Delhi",true],
					["HYD","Hyderabad",true],
				];*/
				var checkCount = 0;
				for(var i = 0; i < cities.length; i++) {
					Ports.findOrCreate({iata_code: cities[i][0]}, { iata_code: cities[i][0] , city_name: cities[i][1], is_inward_port: cities[i][2]}).exec(async(err, ports, wasCreated)=> {
						console.log('created airport');
						checkCount++;
						if(checkCount == cities.length)
							callback(null);
					});
				}
			},
			function(callback) {
				//	adding gst states
				var gststates = [["JAMMU AND KASHMIR", "01"],["HIMACHAL PRADESH", "02"],["PUNJAB", "03"],["CHANDIGARH", "04"],["UTTARAKHAND", "05"],["HARYANA", "06"],["DELHI", "07"],["RAJASTHAN", "08"],["UTTAR  PRADESH", "09"],["BIHAR", "10"],["SIKKIM", "11"],["ARUNACHAL PRADESH", "12"],["NAGALAND", "13"],["MANIPUR", "14"],["MIZORAM", "15"],["TRIPURA", "16"],["MEGHLAYA", "17"],["ASSAM", "18"],["WEST BENGAL", "19"],["JHARKHAND", "20"],["ODISHA", "21"],["CHATTISGARH", "22"],["MADHYA PRADESH", "23"],["GUJARAT", "24"],["DAMAN AND DIU", "25"],["DADRA AND NAGAR HAVELI", "26"],["MAHARASHTRA", "27"],["ANDHRA PRADESH(BEFORE DIVISION)", "28"],["KARNATAKA", "29"],["GOA", "30"],["LAKSHWADEEP", "31"],["KERALA", "32"],["TAMIL NADU", "33"],["PUDUCHERRY", "34"],["ANDAMAN AND NICOBAR ISLANDS", "35"],["TELANGANA", "36"],["ANDHRA PRADESH (NEW)", "37"]];
				var checkCount = 0;
				for(var i = 0; i < gststates.length; i++) {
					Gst.findOrCreate({gst_code: gststates[i][1]}, { gst_code: gststates[i][1] , state_name: gststates[i][0]}).exec(async(err, ports, wasCreated)=> {
						if(err)
							console.log(err)
						else
							console.log('created  gst');

						checkCount++;
						if(checkCount == gststates.length)
							callback(null, "all GST and IATA added");
					});
				}
			}/*,
			function(callback) {
				var exchangerates = [
					{"currency" : "USD", "value_local" : 70, "effective_from" : 1534271400000, "expires_on" : 2556143999000 },
					{"currency" : "INR", "value_local" : 1, "effective_from" : 1534271400000, "expires_on" : 2556143999000 },
					{"currency" : "EURO", "value_local" : 90, "effective_from" : 1534271400000, "expires_on" : 2556143999000 },
				];
				var checkCount = 0;
				for(var i = 0; i < exchangerates.length; i++) {
					ExchangeRates.findOrCreate({"currency" : "INR"}, exchangerates[i]).exec(async(err, exchangerate, wasCreated)=> {
						checkCount++;
						if(checkCount == exchangerates.length)
							callback(null);
					});
				}
			},
			function(callback){
				var constants = [

				{
					"bank_address" : "HDFC Bank,\nMarol Road,\nSai Chembers, Andheri - 400052",
				 	"delivery_address" : "British Airways,\nUnit 1, Sahar Cargo Complex, \nAndheri, Mumbai\nMahrashtra - 400053",
					"customs_address" : "Customs Bombay,\nSahar Complex, Mumbai\nMahrashtra - 400053",
					"registered_address" : "British Airways,\nAndheri, Mumbai\nMahrashtra - 400053",
					"gstin_number" : "27AMRPP9748Q1ZI",
					"hsn" : "8452",
					"igst_percentage" : 18,
					"cgst_percentage" : 9,
					"sgst_percentage" : 9,
					"collect_fees_percentage" : 5,
					"collect_fees_min_usd" : 10,
					"delivery_order_charge" : 1600,
					"delivery_order_charge_baggage" : 1500,
					"break_bulk_charges" : 1400,
					"miscellaneous_charges" : 50,
					"cartage_charge_min_weight" : 50,
					"cartage_charge_min" : 50,
					"cartage_charge_per_kg" : 2,
					"signatory" : "Operations Signatory",
					"designation" : "Operations Designation",
					"iata_code" : "BOM",
					"effective_from" : 1533407400000,
					"tds_allow" : false,
					"tds_percentage" : 10,
					"tds_applied_on" : "net",
					"expires_on" : 2556143999000,
					"direct_delivery_charges": 1300,

					"gst_budget_code": "SCI82",
					"gst_budget_account": "1386",
					"approved_by":	 "Naval Patel",
					"approver_title": "Systems Manager",
					"approver_email": "www.naval.com@gmail.com",
					"intimation_email": "subscribenaval@rediffmail.com",
					"line_manager_email": "veena@mobigic.com"
					//"can_front" : { "ops" : [ { "insert" : "Please come with follow documents:\nDO papers" }, { "attributes" : { "list" : "ordered" }, "insert" : "\n" }, { "insert" : "Identity Proof" }, { "attributes" : { "list" : "ordered" }, "insert" : "\n" }, { "insert" : "Cheque/DD/Cash as applicable" }, { "attributes" : { "list" : "ordered" }, "insert" : "\n" }, { "insert" : "BRO in case it is notify to the Bank" }, { "attributes" : { "list" : "ordered" }, "insert" : "\n" } ] },
					//"can_back" : { "ops" : [ { "insert" : "All the rules and regulations are as follows:\nRule 1Rule 1Rule 1Rule 1Rule 1Rule 1Rule 1Rule 1Rule 1Rule 1Rule 1" }, { "attributes" : { "list" : "ordered" }, "insert" : "\n" }, { "insert" : "Rule 2Rule 2Rule 2Rule 2Rule 2Rule 2Rule 2Rule 2Rule 2Rule 2Rule 2" }, { "attributes" : { "list" : "ordered" }, "insert" : "\n" }, { "insert" : "Rule 3Rule 3Rule 3Rule 3Rule 3Rule 3Rule 3Rule 3Rule 3Rule 3Rule 3" }, { "attributes" : { "list" : "ordered" }, "insert" : "\n" } ] }

				},
				];

				var checkCount = 0;
				CityConstants.findOrCreate({"iata_code" : "BOM"},constants[0]).exec(async(err, constant, wasCreated)=> {
					console.log(wasCreated);
					if(err)
						console.log(err, null);
					console.log('city constant created');

					checkCount++;
					if(checkCount == constants.length)
						callback(null);
				});
			},
			function(callback) {
				var consignee = [
				['BOM','BOM-Direct','BOM Direct Importer\'s line1\nline2\nline3','bom-direct@mobigic.com','400001','9874563210','MAHARASHTRA','27AMRPP7777Q1ZI','none','Direct'],
				['BOM','BOM-Credit','BOM Credit Importer\'s line1\nline2\nline3','bom-credit@mobigic.com','400002','8142536970','MAHARASHTRA','27AMRPP8888Q1ZI','15 Days','Agent'],
				['BOM','GUJ-Bank','GUJ Bank Importer\'s line1\nline2\nline3','guj-bank@mobigic.com','400003','6231472589','GUJARAT','24AMRPP9999Q1ZI','07 Days','Bank'],
				['BOM','SEZ-DirectAgent','SEZ-DirectAgent Importer\'s line1\nline2\nline3','sez-direct-agent@mobigic.com','400004','7012348596','MAHARASHTRA','27AMRPP6666Q1ZI','30 Days','Direct Agent']];

				var checkCount = 0;
				for(var i = 0; i < consignee.length; i++) {
					Address.findOrCreate({city_iata_code: 'NNP'}, {city_iata_code: consignee[i][0],name: consignee[i][1],name_alias: consignee[i][1],address: consignee[i][2],email: consignee[i][3],pincode: consignee[i][4],phone: consignee[i][5],state: consignee[i][6],gstin: consignee[i][7],credit_period: consignee[i][8],type_of_customer: consignee[i][9]}).exec(async(err, ports, wasCreated)=> {
						console.log('created  consignee');
						checkCount++;
						if(checkCount == consignee.length)
							callback(null);
					});
        		}
			},
			function(callback) {
				var reasons = [
					{"reason_type" : "Reasons for voiding Invoice", "reason" : "void invoice reason 1", "make_it_visible" : true },
					{"reason_type" : "Reasons for voiding Invoice", "reason" : "void invoice reason 2", "make_it_visible" : true },
					{"reason_type" : "Reasons for voiding Invoice", "reason" : "void invoice reason 3", "make_it_visible" : true },
					{"reason_type" : "Reasons for voiding DO", "reason" : "void do reason 1", "make_it_visible" : true },
					{"reason_type" : "Reasons for voiding DO", "reason" : "void do reason 2", "make_it_visible" : true },
					{"reason_type" : "Reasons for voiding DO", "reason" : "void do reason 3", "make_it_visible" : true },
					{"reason_type" : "Reasons for voiding AWB", "reason" : "void awb reason 1", "make_it_visible" : true },
					{"reason_type" : "Reasons for voiding AWB", "reason" : "void awb reason 2", "make_it_visible" : true },
					{"reason_type" : "Reasons for voiding AWB", "reason" : "void awb reason 3", "make_it_visible" : true }
				];

				var checkCount = 0;
				for(var i = 0; i < reasons.length; i++) {
					Reasons.create(reasons[i]).fetch().exec(async(err, ports, wasCreated)=> {
						console.log('created reason');
						checkCount++;
						if(checkCount == reasons.length)
							callback(null, "you are set")
					});
        		}
			}*/
		],
		function(err, result){
			if(err)
				console.log(err);
			if(result)
				res.send(result);
		});
	}
};
